export const CONTRACT_ID = "CAIGF53UI7SWZXSQPHJNSYRK7T2AMPWEAF6I6R57IXFDNVQNFQAYF7IA";
export const NATIVE_TOKEN_ID = "CDLZFC3SYJYDZT7K67VZ75HPJVIEUVNIXF47ZG2FB2RMQQVU2HHGCYSC";
export const RPC_URL = "https://soroban-testnet.stellar.org";
export const NETWORK_PASSPHRASE = "Test SDF Network ; September 2015";
